[package]
name = "transfer-hook"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "transfer_hook"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-spl = "0.30.1"
anchor-lang = "0.30.1"
solana-program = "1.17"
spl-transfer-hook-interface = "0.8.2"
spl-tlv-account-resolution = "0.8.1"
spl-type-length-value = "0.6.0"
